### ISSUE TITLE
Parsed colour() messages don't respect formatting codes

### ISSUE THREAD

**Issue by HackuJacku** [EnvyWare/API#14]
Although it is for DexRewards, formatting codes aren't respected. In the following example, the prefix is not bold when it should be. Removing the '&r' puts the message after the prefix in bold when it should not be.

![image](https://user-images.githubusercontent.com/18508413/175838616-235c5583-6873-401e-a2c0-ba989b498c61.png)

**Comment by danorris709** [comment]
Fixed
