### ISSUE TITLE
Typo before 'https' on default "invite to discord message"

### ISSUE THREAD

**Issue by EverNife** [EnvyWare/API#22]
![image](https://user-images.githubusercontent.com/11357801/194804826-f8d490fc-dd01-40da-93a6-4676cea58bbe.png)

https://github.com/EnvyWare/API/blob/main/forge/src/main/java/com/envyful/api/forge/command/command/ForgeCommand.java#L76

**Comment by danorris709** [comment]
Fixed in next version
