### ISSUE TITLE
id from SaveManager#loadAttribute is null

### ISSUE THREAD

**Issue by Razzybazzy1** [EnvyWare/API#33]
After loading a specific player's attribute via SaveManager#loadAttribute, the UUID from id is null. Surely as the UUID has been provided, it would be set and therefore not be null?

**Comment by danorris709** [comment]
Could you show what you're doing please?

**Comment by Razzybazzy1** [comment]
I'm attempting to get every attribute from my plugin, that i currently have to loop through the directory so that it can get all the UUIDs of the players with attributes, and then use getSaveManager().loadAttribute(). After loading the attribute, using the UUID from the file's name, the attribute is loaded by using this.id or this.getId() returns null regardless of if the player is online


java~
if (ConfigProxy.PLAYERDATA.exists() && ConfigProxy.PLAYERDATA.isDirectory()) {
            File[] files = ConfigProxy.PLAYERDATA.listFiles();
            if (files != null) {
                for (File file : files) {
                    UUID uuid = UUID.fromString(file.getName().replace(".json", ""));
                    playerManager.getSaveManager().loadAttribute(AttributeData.class, uuid).whenComplete((attribute, throwable) -> {
                        attribute.setUuid(uuid); // had to add as if using this.id and this.getId() both return null
                        DATA.put(uuid, attribute);
                    });
                }
            }
        }

**Comment by danorris709** [comment]
Does the attribute class extend `PlayerAttribute`? if not then the JsonSaveManager will not update the parent after it is loaded.

**Comment by Razzybazzy1** [comment]
it extends the ManagedForgeAttribute also the player is offline, but i still want to get the UUID

**Comment by danorris709** [comment]
Fixed with https://github.com/EnvyWare/API/pull/38
