### ISSUE TITLE
[Feature]Methods of refreshing GUI

### ISSUE THREAD

**Issue by Lileep** [EnvyWare/API#9]
Hi there, I'm using this API to develop platform independent forge mod and it works well.
The problem is that I have no idea how to refresh gui after click since I need to remove sth from the gui after click.
Have seen that your bingo mod used `GuiFactory.guiBuilder()` and `GuiFactory.paneBuilder()`, there're `clickHandler()`s in every elements which are used to execute some commands, wonder if I can add sth in this code block to implement "remove then refresh" logic.

**Comment by Lileep** [comment]
Have figured out in WonderTrade that it just need to open the GUI again to refresh it.
Another question, do I have to interact with `Thread`s to wait util the database updating finished? Since db accessing is a sole thread, it'll cause asynchronize issue when I write like this:
`result=dataRemoveMethods();
openGUI(result);`
the GUI will show first and it doesn't wait for the result.

**Comment by Lileep** [comment]
Try to use `CountDownLatch` to block the code util db accessing finished but it seems not work.

**Comment by danorris709** [comment]
> Have figured out in WonderTrade that it just need to open the GUI again to refresh it.
> Another question, do I have to interact with `Thread`s to wait util the database updating finished? Since db accessing is a sole thread, it'll cause asynchronize issue when I write like this:
> `result=dataRemoveMethods();
> openGUI(result);`
> the GUI will show first and it doesn't wait for the result.

I'm sorry I don't understand your question here. You're trying to wait for the database query to have finished executing before updating the GUI? If so, why?

**Comment by Lileep** [comment]
> > Have figured out in WonderTrade that it just need to open the GUI again to refresh it.
> > Another question, do I have to interact with `Thread`s to wait util the database updating finished? Since db accessing is a sole thread, it'll cause asynchronize issue when I write like this:
> > `result=dataRemoveMethods(); openGUI(result);`
> > the GUI will show first and it doesn't wait for the result.
> 
> I'm sorry I don't understand your question here. You're trying to wait for the database query to have finished executing before updating the GUI? If so, why?

Yep, that's it. It's because I wanna update sth before GUI is refreshed. e.g., I have a db which collects pixelmon data. I wanna get one and then delete it from db. I use GUI to display Pixelmons in the database, so I need to update the GUI after deletion. Therefore, the GUI should be updated after the query is executed successfully.

**Comment by danorris709** [comment]
Then you need to cache your database values because waiting for the database will be potentially too slow for the UI.

**Comment by Lileep** [comment]
> Then you need to cache your database values because waiting for the database will be potentially too slow for the UI.

Ah, that's it. I'll have a try and close it, thx for answering! :)

**Comment by Lileep** [comment]
Btw, is there a way to close the GUI in a click handler?

**Comment by danorris709** [comment]
No worries, you're welcome to DM on Discord or ask in my discord server if you've got any other questions :))

And yeah use Player#closeScreen (I think have some examples in the GTS and Bungo repos)

**Comment by Lileep** [comment]
> No worries, you're welcome to DM on Discord or ask in my discord server if you've got any other questions :))
> 
> And yeah use Player#closeScreen (I think have some examples in the GTS and Bungo repos)

Got it, it works, thx. XD
Just have joined ur discord today, wish I could make cool projects and benefit others one day.
